# Generated by Django 5.2 on 2025-05-27 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataitem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Unannotated'), (2, 'Annotated'), (3, 'Finished Annotation')], default=1)),
                ('save_finished_annotation', models.BooleanField(default=False)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
                ('annotated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dataitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataitem.dataitem')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_modifiede_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
